import { A1_RE } from '../a1'
export { A1_RE }
export const RANGE_RE = /([A-Z])(\d+):([A-Z])(\d+)/g
const FUNC_NAMES = 'SUMPRODUCT|SAMPLE|WEIGHTAVG|ARRAYTOTEXT|FIRST|LAST|MAX_BY|MIN_BY|MAXLEN|MINLEN|MAXSTR|MINSTR|RANGEHASH|COUNTNUMERIC|RANGEUNIQUE|ENTROPY|JACCARD|RANGESORT|RANGEJSON|RANGECSV|MOSTCOMMON|LEASTCOMMON|COVAR|CORREL|RSQ|EUCLIDEAN|MANHATTAN|CHEBYSHEV|COSINE|DOTPROD|SLOPE|INTERCEPT|SUMXMY2|SUMX2MY2|SUMX2PY2|MINIFS|MAXIFS|COUNTIFS|SUMIFS|SUMIF|COUNTIF|COUNTBLANK|COUNTUNIQUE|AVERAGEIF|COUNTA|SUM|AVERAGE|MIN|MAX|COUNT|MEDIAN|MAXA|MINA|AVERAGEA|MODE|PRODUCT|SUMSQ|GEOMEAN|HARMEAN|AVEDEV|LARGE|SMALL|RANK|SKEW|KURT|GINI|ZSCORE|PERCENTRANK|PERCENTILE|QUARTILE|TRIMMEAN|FORECAST|STDEVP|STDEV|VARP|VAR|ROUNDUP|ROUNDDOWN|ROUND|ABS|FLOOR|CEILING|CEIL|SQRT|CBRT|IF|POWER|MOD|INT|LN|LOG10|LOG2|MAGNITUDE|LOG1P|LOG|EXP10|EXP2|EXPM1|EXP|CONCATENATE|CONCAT|HYPERLINK|IMAGE|URLHOST|URLPATH|URLQUERY|ENCODEURL|DECODEURL|JSONESCAPE|BASE64ENCODE|BASE64DECODE|LEN|UPPER|LOWER|LEFT|RIGHT|MID|CHARAT|FIRSTCHAR|LASTCHAR|TRIM|CLEAN|NORMALIZE|REGEXMATCH|REGEXEXTRACT|REGEXREPLACE|REGEXCOUNT|T|SUBSTITUTE|SPLITN|TEXTBEFORE|TEXTAFTER|WORDCOUNT|OCCURS|INITIALS|DEACCENT|TRUNCATE|SQUEEZE|ROT13|MASK|RANDSTRING|COMMONPREFIX|COMMONSUFFIX|LINECOUNT|CHARCOUNT|LPAD|RPAD|REVERSE|STARTSWITH|ENDSWITH|CONTAINS|FIND|SEARCH|REPT|SLUG|CAMELCASE|SNAKECASE|KEBABCASE|PROPER|TEXTJOIN|JOIN|EXACT|EQUALCI|LEVENSHTEIN|HAMMING|DICE|LCS|SOUNDEX|LIKE|REPLACE|DOLLAR|TEXT|EPOCH|TODAY|NOW|DATEVALUE|DATE|YEAR|MONTH|DAY|DAYS|HOUR|MINUTE|SECOND|TIMEVALUE|TIME|ISOWEEKNUM|WEEKNUM|WEEKDAY|WORKDAY|EDATE|EOMONTH|NETWORKDAYS|DAYS360|DATEDIF|AND|OR|XOR|NOT|TRUE|FALSE|BOOLEAN|YESNO|BOOLTEXT|ISURL|ISEMAIL|ISBLANK|ISNUMBER|ISTEXT|ISERROR|TYPE|NA|CHOOSE|IFEMPTY|COALESCE|ISEVEN|ISODD|ISBETWEEN|IFS|SWITCH|VLOOKUP|HLOOKUP|XLOOKUP|OFFSET|RANGEDIM|INDIRECT|ADDRESS|ISFORMULA|ISREF|ROW|COLUMN|INDEX|MATCH|INRANGE|IFERROR|IFNA|UNICHAR|UNICODE|CHAR|CODE|FORMATBYTES|FORMATDURATION|RELATIVETIME|KORNUM|STARS|PROGRESSBAR|STRINGIFY|RANDCOLOR|HSL|MIX|INVERTCOLOR|LUMA|RGB|LANG|TIMEZONE|NUMBERVALUE|VALUE|N|TRUNC|SIGN|SIGNCHAR|PI|TAU|E|LOGISTIC|RELU|EVEN|ODD|RANDBETWEEN|RANDFLOAT|RAND|COINFLIP|RANDNORM|LERP|INVLERP|MEDIAN3|CLAMP|HYPOT|MAPRANGE|GCD|LCM|EFFECT|NOMINAL|PMT|FV|PV|NPV|IRR|RANDID|ISPRIME|DIGITSUM|UUID|RANDPICK|FACT|COMBIN|PERMUT|BASE|DECIMAL|HEX2DEC|DEC2HEX|BIN2DEC|DEC2BIN|OCT2DEC|DEC2OCT|BIN2HEX|HEX2BIN|OCT2BIN|OCT2HEX|BIN2OCT|HEX2OCT|ROMAN|ARABIC|BITAND|BITOR|BITXOR|BITLSHIFT|BITRSHIFT|MROUND|QUOTIENT|SQRTPI|ASIN|ACOS|ATAN2|ATAN|SINH|COSH|TANH|ASINH|ACOSH|ATANH|ACOTH|ACOT|SECH|CSCH|COTH|SEC|CSC|COT|SIN|COS|TAN|DEGREES|RADIANS'
export const FUNC_RE = new RegExp(`(${FUNC_NAMES})\\(([^()]*)\\)`, 'gi')

export const expandRange = (a: string, ar: string, b: string, br: string): string[] => {
  const c1 = a.charCodeAt(0), c2 = b.charCodeAt(0)
  const r1 = Number(ar), r2 = Number(br)
  const refs: string[] = []
  for (let c = Math.min(c1, c2); c <= Math.max(c1, c2); c++) {
    for (let r = Math.min(r1, r2); r <= Math.max(r1, r2); r++) {
      refs.push(String.fromCharCode(c) + r)
    }
  }
  return refs
}

export const collectRefs = (args: string): string[] => {
  const refs: string[] = []
  args.replace(RANGE_RE, (_x, a, ar, b, br) => {
    refs.push(...expandRange(a, ar, b, br))
    return ''
  })
  args.replace(A1_RE, (_x, c, r) => {
    const ref = `${c}${r}`
    if (!refs.includes(ref)) refs.push(ref)
    return ''
  })
  return refs
}

export function refsInFormula(raw: string): string[] {
  if (!raw.startsWith('=')) return []
  return collectRefs(raw.slice(1))
}
