export const A1_RE = /([A-J])(\d+)/g
export const RANGE_RE = /([A-J])(\d+):([A-J])(\d+)/g
const FUNC_NAMES = 'SUMPRODUCT|SAMPLE|WEIGHTAVG|ARRAYTOTEXT|FIRST|LAST|MAX_BY|MIN_BY|COVAR|CORREL|SLOPE|INTERCEPT|MINIFS|MAXIFS|COUNTIFS|SUMIFS|SUMIF|COUNTIF|COUNTBLANK|COUNTUNIQUE|AVERAGEIF|COUNTA|SUM|AVERAGE|MIN|MAX|COUNT|MEDIAN|MAXA|MINA|AVERAGEA|MODE|PRODUCT|SUMSQ|GEOMEAN|HARMEAN|AVEDEV|LARGE|SMALL|RANK|PERCENTILE|QUARTILE|TRIMMEAN|FORECAST|STDEVP|STDEV|VARP|VAR|ROUNDUP|ROUNDDOWN|ROUND|ABS|FLOOR|CEILING|CEIL|SQRT|IF|POWER|MOD|INT|LN|LOG10|LOG2|LOG|EXP|CONCATENATE|CONCAT|HYPERLINK|ENCODEURL|DECODEURL|JSONESCAPE|BASE64ENCODE|BASE64DECODE|LEN|UPPER|LOWER|LEFT|RIGHT|MID|TRIM|CLEAN|REGEXMATCH|REGEXEXTRACT|REGEXREPLACE|T|SUBSTITUTE|SPLITN|TEXTBEFORE|TEXTAFTER|WORDCOUNT|LPAD|RPAD|REVERSE|STARTSWITH|ENDSWITH|CONTAINS|FIND|SEARCH|REPT|PROPER|TEXTJOIN|JOIN|EXACT|REPLACE|DOLLAR|TEXT|EPOCH|TODAY|NOW|DATEVALUE|DATE|YEAR|MONTH|DAY|DAYS|HOUR|MINUTE|SECOND|TIMEVALUE|TIME|ISOWEEKNUM|WEEKNUM|WEEKDAY|WORKDAY|EDATE|EOMONTH|NETWORKDAYS|DAYS360|DATEDIF|AND|OR|XOR|NOT|TRUE|FALSE|ISURL|ISEMAIL|ISBLANK|ISNUMBER|ISTEXT|ISERROR|TYPE|NA|CHOOSE|IFEMPTY|COALESCE|ISEVEN|ISODD|ISBETWEEN|IFS|SWITCH|VLOOKUP|HLOOKUP|XLOOKUP|OFFSET|INDIRECT|ADDRESS|ISFORMULA|ISREF|ROW|COLUMN|INDEX|MATCH|IFERROR|IFNA|UNICHAR|UNICODE|CHAR|CODE|FORMATBYTES|FORMATDURATION|RELATIVETIME|KORNUM|NUMBERVALUE|VALUE|N|TRUNC|SIGN|PI|EVEN|ODD|RANDBETWEEN|RANDFLOAT|RAND|LERP|CLAMP|HYPOT|MAPRANGE|GCD|LCM|EFFECT|NOMINAL|PMT|FV|PV|NPV|IRR|RANDID|UUID|RANDPICK|FACT|COMBIN|PERMUT|BASE|DECIMAL|HEX2DEC|DEC2HEX|BIN2DEC|DEC2BIN|OCT2DEC|DEC2OCT|BIN2HEX|HEX2BIN|OCT2BIN|OCT2HEX|BIN2OCT|HEX2OCT|ROMAN|ARABIC|BITAND|BITOR|BITXOR|BITLSHIFT|BITRSHIFT|MROUND|QUOTIENT|SQRTPI|ASIN|ACOS|ATAN2|ATAN|SINH|COSH|TANH|ASINH|ACOSH|ATANH|SIN|COS|TAN|DEGREES|RADIANS'
export const FUNC_RE = new RegExp(`(${FUNC_NAMES})\\(([^()]*)\\)`, 'gi')

export const expandRange = (a: string, ar: string, b: string, br: string): string[] => {
  const c1 = a.charCodeAt(0), c2 = b.charCodeAt(0)
  const r1 = Number(ar), r2 = Number(br)
  const refs: string[] = []
  for (let c = Math.min(c1, c2); c <= Math.max(c1, c2); c++) {
    for (let r = Math.min(r1, r2); r <= Math.max(r1, r2); r++) {
      refs.push(String.fromCharCode(c) + r)
    }
  }
  return refs
}

export const collectRefs = (args: string): string[] => {
  const refs: string[] = []
  args.replace(RANGE_RE, (_x, a, ar, b, br) => {
    refs.push(...expandRange(a, ar, b, br))
    return ''
  })
  args.replace(A1_RE, (_x, c, r) => {
    const ref = `${c}${r}`
    if (!refs.includes(ref)) refs.push(ref)
    return ''
  })
  return refs
}

export function refsInFormula(raw: string): string[] {
  if (!raw.startsWith('=')) return []
  return collectRefs(raw.slice(1))
}
